-- Phase 10: Staff & Vendor management. ADMIN-only end to end (same
-- precedent as Expense -- no app screen drives this yet). "Vendor
-- payments" reuses the existing expense table via a new nullable
-- vendor_id FK rather than a new VendorPayment entity -- an expense
-- linked to a vendor IS a vendor payment, same "don't duplicate data
-- that already exists elsewhere" reasoning used for Dashboard's
-- activity feed and Amenity's fee field.

CREATE TABLE staff (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255),
    modified_by character varying(255),
    updated_at timestamp(6) without time zone,
    community_id bigint NOT NULL,
    name character varying(100) NOT NULL,
    role character varying(255) NOT NULL,
    phone_number character varying(255),
    active boolean NOT NULL DEFAULT true,
    CONSTRAINT staff_pkey PRIMARY KEY (id),
    CONSTRAINT staff_role_check CHECK (role IN ('SECURITY', 'HOUSEKEEPING', 'MAINTENANCE', 'OTHER')),
    CONSTRAINT fk_staff_community FOREIGN KEY (community_id) REFERENCES community(id)
);

CREATE TABLE staff_attendance (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255),
    modified_by character varying(255),
    updated_at timestamp(6) without time zone,
    community_id bigint NOT NULL,
    staff_id bigint NOT NULL,
    attendance_date date NOT NULL,
    status character varying(255) NOT NULL,
    marked_by_member_id bigint NOT NULL,
    CONSTRAINT staff_attendance_pkey PRIMARY KEY (id),
    CONSTRAINT staff_attendance_status_check CHECK (status IN ('PRESENT', 'ABSENT', 'HALF_DAY', 'ON_LEAVE')),
    CONSTRAINT uk_staff_attendance_staff_date UNIQUE (staff_id, attendance_date),
    CONSTRAINT fk_staff_attendance_community FOREIGN KEY (community_id) REFERENCES community(id),
    CONSTRAINT fk_staff_attendance_staff FOREIGN KEY (staff_id) REFERENCES staff(id),
    CONSTRAINT fk_staff_attendance_marked_by_member FOREIGN KEY (marked_by_member_id) REFERENCES community_member(id)
);

CREATE TABLE vendor (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255),
    modified_by character varying(255),
    updated_at timestamp(6) without time zone,
    community_id bigint NOT NULL,
    name character varying(100) NOT NULL,
    service_type character varying(100) NOT NULL,
    contact_person character varying(255),
    phone_number character varying(255),
    active boolean NOT NULL DEFAULT true,
    CONSTRAINT vendor_pkey PRIMARY KEY (id),
    CONSTRAINT fk_vendor_community FOREIGN KEY (community_id) REFERENCES community(id)
);

ALTER TABLE expense ADD COLUMN vendor_id bigint;
ALTER TABLE expense ADD CONSTRAINT fk_expense_vendor FOREIGN KEY (vendor_id) REFERENCES vendor(id);

CREATE INDEX idx_staff_community_name ON staff (community_id, name);
CREATE INDEX idx_staff_attendance_staff_date ON staff_attendance (staff_id, attendance_date DESC);
CREATE INDEX idx_vendor_community_name ON vendor (community_id, name);
CREATE INDEX idx_expense_vendor ON expense (vendor_id);
