-- Phase 11: Community Documents. Metadata only -- the actual file bytes
-- live in S3 (bucket/region/credentials configured outside this schema),
-- keyed by s3_key. ADMIN uploads/deletes; visibility (ALL_MEMBERS vs
-- ADMIN_ONLY) is enforced in application code on every read path.

CREATE TABLE community_document (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255),
    modified_by character varying(255),
    updated_at timestamp(6) without time zone,
    community_id bigint NOT NULL,
    title character varying(255) NOT NULL,
    description character varying(255),
    category character varying(100) NOT NULL,
    visibility character varying(255) DEFAULT 'ALL_MEMBERS' NOT NULL,
    s3_key character varying(500) NOT NULL,
    content_type character varying(255) NOT NULL,
    file_size_bytes bigint NOT NULL,
    uploaded_by_member_id bigint NOT NULL,
    CONSTRAINT community_document_pkey PRIMARY KEY (id),
    CONSTRAINT community_document_visibility_check CHECK (visibility IN ('ALL_MEMBERS', 'ADMIN_ONLY')),
    CONSTRAINT fk_community_document_community FOREIGN KEY (community_id) REFERENCES community(id),
    CONSTRAINT fk_community_document_uploaded_by_member FOREIGN KEY (uploaded_by_member_id) REFERENCES community_member(id)
);

CREATE INDEX idx_community_document_community_created_at ON community_document (community_id, created_at DESC);
