-- Phase 12: Structured units + area-based billing. Community.totalUnits was
-- only ever a plain count and Bill generation could only apply one flat
-- amount per batch, since there was no per-unit size to vary it by. Adds a
-- Unit master-data table (block/floor/area/type) and an optional unit_id
-- link from community_member (unitNumber stays as the free-text field every
-- member has had since Phase 1 -- linking a structured Unit is an explicit
-- admin action, not required). Community gains a billing_mode toggle
-- (FLAT, the existing/default behavior most communities want, or PER_AREA,
-- amount = rate_per_sqft x the member's unit area) and rate_per_sqft, only
-- meaningful in PER_AREA mode.

CREATE TABLE unit (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255),
    modified_by character varying(255),
    updated_at timestamp(6) without time zone,
    community_id bigint NOT NULL,
    unit_number character varying(255) NOT NULL,
    block character varying(255),
    floor integer,
    area_sqft numeric(10,2),
    unit_type character varying(255),
    active boolean NOT NULL DEFAULT true,
    CONSTRAINT unit_pkey PRIMARY KEY (id),
    CONSTRAINT uk_unit_community_number UNIQUE (community_id, unit_number),
    CONSTRAINT fk_unit_community FOREIGN KEY (community_id) REFERENCES community(id)
);

ALTER TABLE community_member ADD COLUMN unit_id bigint;
ALTER TABLE community_member ADD CONSTRAINT fk_community_member_unit FOREIGN KEY (unit_id) REFERENCES unit(id);

ALTER TABLE community ADD COLUMN billing_mode character varying(255) NOT NULL DEFAULT 'FLAT';
ALTER TABLE community ADD COLUMN rate_per_sqft numeric(10,2);
ALTER TABLE community ADD CONSTRAINT community_billing_mode_check CHECK (billing_mode IN ('FLAT', 'PER_AREA'));

CREATE INDEX idx_unit_community_number ON unit (community_id, unit_number);
CREATE INDEX idx_community_member_unit ON community_member (unit_id);
