-- Phase 13: Committee/RWA. A directory + term-tracking layer only -- a
-- CommitteeMember seat is layered on an existing CommunityMember (ADMIN
-- or RESIDENT) and grants no extra authorization in this phase, keeping
-- the existing two-role (ADMIN/RESIDENT) model intact rather than a much
-- larger authorization change touching every service. ADMIN manages
-- (create/end-term), any ACTIVE member browses the directory (member-
-- facing, unlike Staff/Vendor's back-office data). No hard delete, same
-- precedent as Amenity/Staff/Vendor/Unit -- correcting a mistaken entry
-- is done via end-term.

CREATE TABLE committee_member (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255),
    modified_by character varying(255),
    updated_at timestamp(6) without time zone,
    community_id bigint NOT NULL,
    member_id bigint NOT NULL,
    position character varying(255) NOT NULL,
    custom_position character varying(255),
    term_start date NOT NULL,
    term_end date,
    CONSTRAINT committee_member_pkey PRIMARY KEY (id),
    CONSTRAINT committee_member_position_check CHECK (position IN
        ('PRESIDENT', 'VICE_PRESIDENT', 'SECRETARY', 'JOINT_SECRETARY', 'TREASURER', 'COMMITTEE_MEMBER', 'OTHER')),
    CONSTRAINT fk_committee_member_community FOREIGN KEY (community_id) REFERENCES community(id),
    CONSTRAINT fk_committee_member_member FOREIGN KEY (member_id) REFERENCES community_member(id)
);

-- Enforces "one current position per member" at the DB level too (not
-- just in the service layer) -- a partial unique index since only rows
-- with term_end IS NULL should conflict.
CREATE UNIQUE INDEX uk_committee_member_current ON committee_member (member_id) WHERE term_end IS NULL;

CREATE INDEX idx_committee_member_community ON committee_member (community_id, term_end);
