-- Phase 14: Push notifications. device_token is identity-scoped, not
-- community-scoped -- one person's device works across every community
-- they belong to, so this doesn't hang off community_id like every
-- other table so far. Registering an existing (identity_id, device_id)
-- pair upserts the fcm_token rather than creating a new row, since FCM
-- tokens rotate over a device's lifetime.

CREATE TABLE device_token (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255),
    modified_by character varying(255),
    updated_at timestamp(6) without time zone,
    identity_id character varying(255) NOT NULL,
    device_id character varying(255) NOT NULL,
    fcm_token character varying(4096) NOT NULL,
    platform character varying(255) NOT NULL,
    CONSTRAINT device_token_pkey PRIMARY KEY (id),
    CONSTRAINT device_token_platform_check CHECK (platform IN ('ANDROID')),
    CONSTRAINT uk_device_token_identity_device UNIQUE (identity_id, device_id)
);

CREATE INDEX idx_device_token_identity ON device_token (identity_id);
