-- Phase 15: persisted notification history, backing the Android app's
-- bell-icon list. Identity-scoped like device_token (a person's history
-- spans every community they belong to), but each row also carries the
-- community it's about (with the name denormalized so listing never needs
-- a join).

CREATE TABLE notification (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255),
    modified_by character varying(255),
    updated_at timestamp(6) without time zone,
    community_id bigint NOT NULL,
    community_name character varying(255) NOT NULL,
    recipient_identity_id character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    reference_id bigint,
    title character varying(255) NOT NULL,
    body character varying(1000) NOT NULL,
    read boolean NOT NULL DEFAULT false,
    CONSTRAINT notification_pkey PRIMARY KEY (id),
    CONSTRAINT notification_type_check CHECK (type IN (
        'ANNOUNCEMENT', 'BILL_GENERATED', 'PAYMENT_RECORDED',
        'COMPLAINT_RAISED', 'COMPLAINT_ASSIGNED', 'COMPLAINT_STATUS_UPDATED',
        'JOIN_REQUEST_SUBMITTED', 'JOIN_REQUEST_APPROVED', 'JOIN_REQUEST_REJECTED',
        'BOOKING_APPROVED', 'BOOKING_REJECTED', 'VISITOR_ARRIVED'
    ))
);

CREATE INDEX idx_notification_recipient ON notification (recipient_identity_id);
