-- Baseline migration capturing the schema as it exists after Phase 1
-- (Community + CommunityMember, unit-owner onboarding). Generated from
-- `pg_dump --schema-only` against the live dev database and cleaned up.
--
-- This is a baseline (see spring.flyway.baseline-version=1): on the
-- existing dev database, Flyway marks this as already-applied without
-- running it. On a fresh database it runs for real and creates everything
-- from scratch. Either way the end state after V1 is identical.

CREATE TABLE community (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255),
    modified_by character varying(255),
    updated_at timestamp(6) without time zone,
    area character varying(255) NOT NULL,
    district character varying(255) NOT NULL,
    landmark character varying(255),
    name character varying(255) NOT NULL,
    pincode character varying(255) NOT NULL,
    state character varying(255) NOT NULL,
    street character varying(255) NOT NULL,
    total_units integer NOT NULL,
    CONSTRAINT community_pkey PRIMARY KEY (id)
);

CREATE TABLE community_member (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255),
    modified_by character varying(255),
    updated_at timestamp(6) without time zone,
    identity_id character varying(255),
    mobile_number character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    status character varying(255) DEFAULT 'INVITED' NOT NULL,
    unit_number character varying(255) NOT NULL,
    community_id bigint NOT NULL,
    CONSTRAINT community_member_pkey PRIMARY KEY (id),
    CONSTRAINT community_member_role_check CHECK (role IN ('ADMIN', 'OWNER')),
    CONSTRAINT community_member_status_check CHECK (status IN ('INVITED', 'ACTIVE')),
    CONSTRAINT uk_community_member_community_mobile UNIQUE (community_id, mobile_number),
    CONSTRAINT fk_community_member_community FOREIGN KEY (community_id) REFERENCES community(id)
);
