-- Renames CommunityRole.OWNER -> RESIDENT (a resident isn't necessarily
-- the unit owner), adds CommunityMember.email for self-service profile
-- completion, and adds community_join_request for the "I wasn't invited,
-- let me ask to join" flow triggered when community registration detects
-- a duplicate (name, pincode).

ALTER TABLE community_member DROP CONSTRAINT community_member_role_check;
UPDATE community_member SET role = 'RESIDENT' WHERE role = 'OWNER';
ALTER TABLE community_member ADD CONSTRAINT community_member_role_check CHECK (role IN ('ADMIN', 'RESIDENT'));

ALTER TABLE community_member ADD COLUMN email character varying(255);

CREATE TABLE community_join_request (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255),
    modified_by character varying(255),
    updated_at timestamp(6) without time zone,
    community_id bigint NOT NULL,
    requester_identity_id character varying(255) NOT NULL,
    requester_mobile_number character varying(255) NOT NULL,
    requester_name character varying(255) NOT NULL,
    status character varying(255) DEFAULT 'PENDING' NOT NULL,
    CONSTRAINT community_join_request_pkey PRIMARY KEY (id),
    CONSTRAINT community_join_request_status_check CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT fk_community_join_request_community FOREIGN KEY (community_id) REFERENCES community(id)
);

-- Only one outstanding (PENDING) request per identity per community --
-- a past REJECTED request shouldn't block asking again.
CREATE UNIQUE INDEX uk_community_join_request_pending
    ON community_join_request (community_id, requester_identity_id)
    WHERE status = 'PENDING';
