-- Phase 2: Announcements / notice board. ADMIN posts, any ACTIVE member
-- reads. posted_by_member_id references the poster's CommunityMember row
-- (not the auth Identity UUID) so a display name is available without a
-- second call to auth-service.

CREATE TABLE announcement (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255),
    modified_by character varying(255),
    updated_at timestamp(6) without time zone,
    community_id bigint NOT NULL,
    title character varying(255) NOT NULL,
    body text NOT NULL,
    posted_by_member_id bigint NOT NULL,
    CONSTRAINT announcement_pkey PRIMARY KEY (id),
    CONSTRAINT fk_announcement_community FOREIGN KEY (community_id) REFERENCES community(id),
    CONSTRAINT fk_announcement_posted_by_member FOREIGN KEY (posted_by_member_id) REFERENCES community_member(id)
);

CREATE INDEX idx_announcement_community_created_at ON announcement (community_id, created_at DESC);
