-- Phase 3: Maintenance & Billing (generation + status only -- no payment
-- gateway, no separate Payment/receipt entity yet, that's Phase 4). One
-- Bill per ACTIVE member per period, a single flat amount per generation
-- batch since Community has no per-unit size/area field to vary it by.

CREATE TABLE bill (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255),
    modified_by character varying(255),
    updated_at timestamp(6) without time zone,
    community_id bigint NOT NULL,
    member_id bigint NOT NULL,
    period character varying(255) NOT NULL,
    amount numeric(12,2) NOT NULL,
    status character varying(255) DEFAULT 'PENDING' NOT NULL,
    due_date date NOT NULL,
    paid_at timestamp(6) without time zone,
    CONSTRAINT bill_pkey PRIMARY KEY (id),
    CONSTRAINT bill_status_check CHECK (status IN ('PENDING', 'PAID')),
    CONSTRAINT uk_bill_member_period UNIQUE (member_id, period),
    CONSTRAINT fk_bill_community FOREIGN KEY (community_id) REFERENCES community(id),
    CONSTRAINT fk_bill_member FOREIGN KEY (member_id) REFERENCES community_member(id)
);

CREATE INDEX idx_bill_community_period ON bill (community_id, period);
