-- Phase 4: Payments against Bills (method, reference, receipts). One
-- full payment per bill in v1 (unique on bill_id) -- no partial
-- payments. Replaces Phase 3's bare PATCH .../bills/{id}/mark-paid,
-- which is removed in this same change (no external caller yet -- the
-- mobile app still has no networking code).

CREATE TABLE payment (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255),
    modified_by character varying(255),
    updated_at timestamp(6) without time zone,
    community_id bigint NOT NULL,
    bill_id bigint NOT NULL,
    amount numeric(12,2) NOT NULL,
    method character varying(255) NOT NULL,
    reference character varying(255),
    paid_at timestamp(6) without time zone NOT NULL,
    recorded_by_member_id bigint NOT NULL,
    CONSTRAINT payment_pkey PRIMARY KEY (id),
    CONSTRAINT payment_method_check CHECK (method IN ('CASH', 'BANK_TRANSFER', 'UPI', 'CHEQUE', 'OTHER')),
    CONSTRAINT uk_payment_bill UNIQUE (bill_id),
    CONSTRAINT fk_payment_community FOREIGN KEY (community_id) REFERENCES community(id),
    CONSTRAINT fk_payment_bill FOREIGN KEY (bill_id) REFERENCES bill(id),
    CONSTRAINT fk_payment_recorded_by_member FOREIGN KEY (recorded_by_member_id) REFERENCES community_member(id)
);

CREATE INDEX idx_payment_community_paid_at ON payment (community_id, paid_at DESC);
