-- Phase 5: Expenses. ADMIN-only end to end (create/list/get/delete) --
-- expenses belong to the community as a whole, not an individual member,
-- so there's no resident-facing "my expenses" read path.

CREATE TABLE expense (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255),
    modified_by character varying(255),
    updated_at timestamp(6) without time zone,
    community_id bigint NOT NULL,
    category character varying(100) NOT NULL,
    description text NOT NULL,
    amount numeric(12,2) NOT NULL,
    expense_date date NOT NULL,
    created_by_member_id bigint NOT NULL,
    CONSTRAINT expense_pkey PRIMARY KEY (id),
    CONSTRAINT fk_expense_community FOREIGN KEY (community_id) REFERENCES community(id),
    CONSTRAINT fk_expense_created_by_member FOREIGN KEY (created_by_member_id) REFERENCES community_member(id)
);

CREATE INDEX idx_expense_community_expense_date ON expense (community_id, expense_date DESC);
