-- Phase 7: Visitor / Gate Management. Any ACTIVE member logs/checks-in/
-- checks-out their own visitors (host = caller); ADMIN sees and can act
-- on all of them, standing in for a dedicated gate-guard role this
-- system doesn't have yet.

CREATE TABLE visitor (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255),
    modified_by character varying(255),
    updated_at timestamp(6) without time zone,
    community_id bigint NOT NULL,
    host_member_id bigint NOT NULL,
    guest_name character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    purpose character varying(255),
    status character varying(255) DEFAULT 'EXPECTED' NOT NULL,
    entry_time timestamp(6) without time zone,
    exit_time timestamp(6) without time zone,
    CONSTRAINT visitor_pkey PRIMARY KEY (id),
    CONSTRAINT visitor_type_check CHECK (type IN ('GUEST', 'DELIVERY', 'STAFF', 'OTHER')),
    CONSTRAINT visitor_status_check CHECK (status IN ('EXPECTED', 'CHECKED_IN', 'CHECKED_OUT')),
    CONSTRAINT fk_visitor_community FOREIGN KEY (community_id) REFERENCES community(id),
    CONSTRAINT fk_visitor_host_member FOREIGN KEY (host_member_id) REFERENCES community_member(id)
);

CREATE INDEX idx_visitor_community_created_at ON visitor (community_id, created_at DESC);
CREATE INDEX idx_visitor_host_created_at ON visitor (host_member_id, created_at DESC);
