-- Phase 8: Amenities. Amenity is ADMIN-managed master data, browsable by
-- any ACTIVE member. AmenityBooking mirrors community_join_request's
-- PENDING/APPROVED/REJECTED lifecycle, plus CANCELLED for the booker (or
-- ADMIN) to withdraw a PENDING/APPROVED booking.

CREATE TABLE amenity (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255),
    modified_by character varying(255),
    updated_at timestamp(6) without time zone,
    community_id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description character varying(255),
    is_paid boolean NOT NULL DEFAULT false,
    fee numeric(12,2),
    rules character varying(255),
    active boolean NOT NULL DEFAULT true,
    CONSTRAINT amenity_pkey PRIMARY KEY (id),
    CONSTRAINT fk_amenity_community FOREIGN KEY (community_id) REFERENCES community(id)
);

CREATE TABLE amenity_booking (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255),
    modified_by character varying(255),
    updated_at timestamp(6) without time zone,
    community_id bigint NOT NULL,
    amenity_id bigint NOT NULL,
    member_id bigint NOT NULL,
    booking_date date NOT NULL,
    slot character varying(100) NOT NULL,
    status character varying(255) DEFAULT 'PENDING' NOT NULL,
    CONSTRAINT amenity_booking_pkey PRIMARY KEY (id),
    CONSTRAINT amenity_booking_status_check CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')),
    CONSTRAINT fk_amenity_booking_community FOREIGN KEY (community_id) REFERENCES community(id),
    CONSTRAINT fk_amenity_booking_amenity FOREIGN KEY (amenity_id) REFERENCES amenity(id),
    CONSTRAINT fk_amenity_booking_member FOREIGN KEY (member_id) REFERENCES community_member(id)
);

CREATE INDEX idx_amenity_booking_community_date ON amenity_booking (community_id, booking_date DESC);
CREATE INDEX idx_amenity_booking_member_date ON amenity_booking (member_id, booking_date DESC);
CREATE INDEX idx_amenity_booking_conflict_check ON amenity_booking (amenity_id, booking_date, slot, status);
