-- Phase 9: Helpdesk / Complaints. Any ACTIVE member raises a complaint;
-- ADMIN triages (assign/status). Visible to ADMIN, the raiser, or the
-- current assignee. Status is strictly linear: OPEN -> IN_PROGRESS ->
-- RESOLVED -> CLOSED, one step at a time -- no skipping or reopening in
-- this phase. SLA/TAT tracking and reporting are deliberately not built
-- here (would be a natural Dashboard-style follow-up once this data
-- exists, same as Phase 6 was for Bills/Payments/Expenses).

CREATE TABLE complaint (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255),
    modified_by character varying(255),
    updated_at timestamp(6) without time zone,
    community_id bigint NOT NULL,
    raised_by_member_id bigint NOT NULL,
    category character varying(100) NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    priority character varying(255) DEFAULT 'MEDIUM' NOT NULL,
    status character varying(255) DEFAULT 'OPEN' NOT NULL,
    assigned_to_member_id bigint,
    CONSTRAINT complaint_pkey PRIMARY KEY (id),
    CONSTRAINT complaint_priority_check CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'URGENT')),
    CONSTRAINT complaint_status_check CHECK (status IN ('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED')),
    CONSTRAINT fk_complaint_community FOREIGN KEY (community_id) REFERENCES community(id),
    CONSTRAINT fk_complaint_raised_by_member FOREIGN KEY (raised_by_member_id) REFERENCES community_member(id),
    CONSTRAINT fk_complaint_assigned_to_member FOREIGN KEY (assigned_to_member_id) REFERENCES community_member(id)
);

CREATE TABLE complaint_comment (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255),
    modified_by character varying(255),
    updated_at timestamp(6) without time zone,
    complaint_id bigint NOT NULL,
    author_member_id bigint NOT NULL,
    comment text NOT NULL,
    CONSTRAINT complaint_comment_pkey PRIMARY KEY (id),
    CONSTRAINT fk_complaint_comment_complaint FOREIGN KEY (complaint_id) REFERENCES complaint(id),
    CONSTRAINT fk_complaint_comment_author_member FOREIGN KEY (author_member_id) REFERENCES community_member(id)
);

CREATE INDEX idx_complaint_community_created_at ON complaint (community_id, created_at DESC);
CREATE INDEX idx_complaint_raised_by_created_at ON complaint (raised_by_member_id, created_at DESC);
CREATE INDEX idx_complaint_comment_complaint_created_at ON complaint_comment (complaint_id, created_at ASC);
