spring:
  config:
    import:
      - "optional:vault://"
      - "optional:configserver:${CONFIG_SERVER_URL:http://localhost:9002}"
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    io.micrometer.tracing: DEBUG
    org.springframework.boot.actuate.tracing: DEBUG
