spring:
  config:
    import:
      - "vault://"
      - "optional:configserver:${CONFIG_SERVER_URL:http://localhost:9002}"
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

management:
  tracing:
    sampling:
      probability: 0.1
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: WARN
    com.raitukashtam: INFO
