services:
  postgres:
    image: postgres:15
    container_name: mycommunity-service-pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: mycommunity-service-db
      POSTGRES_USER: mycommunity-service-user
      POSTGRES_PASSWORD: mycommunity-service-password
      TZ: Asia/Kolkata
      PGTZ: 'Asia/Kolkata'
      POSTGRES_INITDB_ARGS: '--data-checksums --encoding=UTF8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8 --no-locale'
    command: ["postgres", "-c", "timezone=+05:30", "-c", "log_timezone=+05:30"]
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mycommunity-service-user -d mycommunity-service-db"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pgdata:
