spring:
  config:
    import:
      - "optional:vault://"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework.web: DEBUG
    com.raitukashtam.jwt.filter: DEBUG
    io.micrometer.tracing: DEBUG
    org.springframework.boot.actuate.tracing: DEBUG
