-- Baseline migration capturing the schema as it exists after Phase 0-2 of
-- the multi-product identity platform redesign (see
-- docs/design/multi-product-identity-platform.md). Generated from
-- `pg_dump --schema-only` against the live dev database and cleaned up.
--
-- This is a baseline (see spring.flyway.baseline-version=1): on the
-- existing dev database, Flyway marks this as already-applied without
-- running it. On a fresh database it runs for real and creates everything
-- from scratch. Either way the end state after V1 is identical.

CREATE TABLE app_user (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255),
    modified_by character varying(255),
    updated_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    is_locked boolean DEFAULT false NOT NULL,
    last_name character varying(255) NOT NULL,
    mobile_number character varying(255),
    password character varying(255),
    role character varying(255) DEFAULT 'CONSUMER' NOT NULL,
    verified boolean NOT NULL,
    tenant_code character varying(255),
    identity_id uuid,
    CONSTRAINT app_user_pkey PRIMARY KEY (id),
    CONSTRAINT app_user_role_check CHECK (role IN ('ADMIN', 'FARMER', 'BUYER', 'DELIVERY_PARTNER', 'CONSUMER')),
    CONSTRAINT uk_app_user_email UNIQUE (email),
    CONSTRAINT uk_app_user_mobile_number UNIQUE (mobile_number)
);

CREATE TABLE identity (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255),
    modified_by character varying(255),
    updated_at timestamp(6) without time zone,
    primary_email character varying(255) NOT NULL,
    primary_phone character varying(255),
    status character varying(255) DEFAULT 'ACTIVE' NOT NULL,
    CONSTRAINT identity_pkey PRIMARY KEY (id),
    CONSTRAINT identity_status_check CHECK (status IN ('ACTIVE', 'SUSPENDED')),
    CONSTRAINT uk_identity_primary_email UNIQUE (primary_email)
);

CREATE TABLE identity_credential (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255),
    modified_by character varying(255),
    updated_at timestamp(6) without time zone,
    credential_type character varying(255) NOT NULL,
    external_subject character varying(255),
    password_hash character varying(255),
    verified boolean NOT NULL,
    identity_id uuid NOT NULL,
    CONSTRAINT identity_credential_pkey PRIMARY KEY (id),
    CONSTRAINT identity_credential_credential_type_check CHECK (credential_type IN ('PASSWORD', 'GOOGLE', 'APPLE', 'PASSKEY', 'OTP_PHONE')),
    CONSTRAINT uk_identity_credential_type_subject UNIQUE (credential_type, external_subject),
    CONSTRAINT fk_identity_credential_identity FOREIGN KEY (identity_id) REFERENCES identity(id)
);

CREATE TABLE login_attempt (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255),
    modified_by character varying(255),
    updated_at timestamp(6) without time zone,
    attempt_time timestamp(6) with time zone NOT NULL,
    failure_reason character varying(255),
    ip_address character varying(255) NOT NULL,
    successful boolean NOT NULL,
    user_agent character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT login_attempt_pkey PRIMARY KEY (id),
    CONSTRAINT fk_login_attempt_user FOREIGN KEY (user_id) REFERENCES app_user(id)
);

CREATE TABLE product (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255),
    modified_by character varying(255),
    updated_at timestamp(6) without time zone,
    code character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    status character varying(255) DEFAULT 'ACTIVE' NOT NULL,
    CONSTRAINT product_pkey PRIMARY KEY (id),
    CONSTRAINT product_status_check CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT uk_product_code UNIQUE (code)
);

CREATE TABLE product_membership (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255),
    modified_by character varying(255),
    updated_at timestamp(6) without time zone,
    joined_at timestamp(6) without time zone NOT NULL,
    status character varying(255) DEFAULT 'ACTIVE' NOT NULL,
    product_id bigint NOT NULL,
    identity_id uuid,
    CONSTRAINT product_membership_pkey PRIMARY KEY (id),
    CONSTRAINT product_membership_status_check CHECK (status IN ('ACTIVE', 'SUSPENDED', 'PENDING')),
    CONSTRAINT uk_product_membership_identity_product UNIQUE (identity_id, product_id),
    CONSTRAINT fk_product_membership_product FOREIGN KEY (product_id) REFERENCES product(id),
    CONSTRAINT fk_product_membership_identity FOREIGN KEY (identity_id) REFERENCES identity(id)
);

CREATE TABLE refresh_token (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    expiry_time timestamp(6) with time zone NOT NULL,
    revoked boolean NOT NULL,
    role character varying(255),
    family_id uuid NOT NULL,
    token_hash character varying(64) NOT NULL,
    identity_id uuid NOT NULL,
    CONSTRAINT refresh_token_pkey PRIMARY KEY (id),
    CONSTRAINT uk_refresh_token_hash UNIQUE (token_hash)
);

CREATE TABLE revoked_tokens (
    jti character varying(255) NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT revoked_tokens_pkey PRIMARY KEY (jti)
);

CREATE TABLE tenant (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255),
    modified_by character varying(255),
    updated_at timestamp(6) without time zone,
    is_active boolean NOT NULL,
    code character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    pincode character varying(255),
    region character varying(255),
    product_id bigint,
    CONSTRAINT tenant_pkey PRIMARY KEY (id),
    CONSTRAINT uk_tenant_code UNIQUE (code),
    CONSTRAINT fk_tenant_product FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE token_blacklist (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    expiry_time timestamp(6) with time zone,
    token character varying(500)
);

ALTER TABLE app_user
    ADD CONSTRAINT fk_app_user_tenant FOREIGN KEY (tenant_code) REFERENCES tenant(code);

ALTER TABLE app_user
    ADD CONSTRAINT fk_app_user_identity FOREIGN KEY (identity_id) REFERENCES identity(id);
