-- Phase 3 of the multi-product identity platform redesign: roles become
-- data instead of the compiled UserRole enum. See
-- docs/design/multi-product-identity-platform.md section 4, Phase 3.
--
-- Split from V4 (which drops the now-superseded app_user.role /
-- refresh_token.role columns) so the backfill below can still read
-- app_user.role while it does its work.

CREATE TABLE role (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255),
    modified_by character varying(255),
    updated_at timestamp(6) without time zone,
    code character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT role_pkey PRIMARY KEY (id),
    CONSTRAINT uk_role_product_code UNIQUE (product_id, code),
    CONSTRAINT fk_role_product FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE role_assignment (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255),
    modified_by character varying(255),
    updated_at timestamp(6) without time zone,
    product_membership_id bigint NOT NULL,
    role_id bigint NOT NULL,
    CONSTRAINT role_assignment_pkey PRIMARY KEY (id),
    CONSTRAINT uk_role_assignment_membership_role UNIQUE (product_membership_id, role_id),
    CONSTRAINT fk_role_assignment_membership FOREIGN KEY (product_membership_id) REFERENCES product_membership(id),
    CONSTRAINT fk_role_assignment_role FOREIGN KEY (role_id) REFERENCES role(id)
);

ALTER TABLE identity
    ADD COLUMN is_platform_admin boolean DEFAULT false NOT NULL;

-- Seed the 5 role codes that used to be the UserRole enum, scoped to the
-- RAITUKASHTAM product (raitukashtam.default-product-code).
INSERT INTO role (created_at, created_by, product_id, code, name)
SELECT now(), 'system-migration-v3', p.id, codes.code, codes.name
FROM product p
CROSS JOIN (VALUES
    ('ADMIN', 'Admin'),
    ('FARMER', 'Farmer'),
    ('BUYER', 'Buyer'),
    ('DELIVERY_PARTNER', 'Delivery Partner'),
    ('CONSUMER', 'Consumer')
) AS codes(code, name)
WHERE p.code = 'RAITUKASHTAM';

-- Backfill role_assignment from every existing (app_user.role, product_membership) pair.
INSERT INTO role_assignment (created_at, created_by, product_membership_id, role_id)
SELECT now(), 'system-migration-v3', pm.id, r.id
FROM product_membership pm
JOIN app_user au ON au.identity_id = pm.identity_id
JOIN role r ON r.product_id = pm.product_id AND r.code = au.role
WHERE pm.identity_id IS NOT NULL;

-- Backfill the platform-admin axis: anyone who was app_user.role = 'ADMIN'
-- today only ever used that role to reach auth-service's own tenant/product
-- management endpoints (see SecurityConfig) -- i.e. they were already
-- acting as a platform admin, just via the wrong axis.
UPDATE identity i
SET is_platform_admin = true
FROM app_user au
WHERE au.identity_id = i.id AND au.role = 'ADMIN';
