-- Phase 4b: backs ReuseDetectingAuthorizationService, which wraps Spring
-- Authorization Server's JdbcOAuth2AuthorizationService to reproduce
-- Phase 0's refresh-token reuse detection (replaying a rotated-away
-- token revokes the whole session) -- a property Spring's own rotation
-- does not provide, since it overwrites the refresh token value in
-- place rather than keeping history.

CREATE TABLE refresh_token_ledger (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token_hash character varying(64) NOT NULL,
    authorization_id character varying(100) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT refresh_token_ledger_pkey PRIMARY KEY (id),
    CONSTRAINT uk_refresh_token_ledger_hash UNIQUE (token_hash)
);
