-- Phase 4a of the multi-product identity platform redesign: a Client
-- registry backing Spring Authorization Server's RegisteredClientRepository.
-- See docs/design/multi-product-identity-platform.md section 4, Phase 4,
-- and the Phase 4a plan for why grant types are derived from client_type
-- rather than stored separately.

CREATE TABLE client (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255),
    modified_by character varying(255),
    updated_at timestamp(6) without time zone,
    client_id character varying(255) NOT NULL,
    client_type character varying(255) NOT NULL,
    client_secret_hash character varying(255),
    access_token_ttl_seconds integer NOT NULL,
    refresh_token_ttl_seconds integer NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT client_pkey PRIMARY KEY (id),
    CONSTRAINT client_type_check CHECK (client_type IN ('WEB_SPA', 'ANDROID', 'IOS', 'BACKEND_SERVICE')),
    CONSTRAINT uk_client_client_id UNIQUE (client_id),
    CONSTRAINT fk_client_product FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE client_redirect_uri (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255),
    modified_by character varying(255),
    updated_at timestamp(6) without time zone,
    client_id bigint NOT NULL,
    uri character varying(500) NOT NULL,
    CONSTRAINT client_redirect_uri_pkey PRIMARY KEY (id),
    CONSTRAINT fk_client_redirect_uri_client FOREIGN KEY (client_id) REFERENCES client(id)
);
