services:
  postgres:
    image: postgres:15
    container_name: jwt_auth_pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: jwt_auth_db
      POSTGRES_USER: jwt_user
      POSTGRES_PASSWORD: jwt_password
      TZ: Asia/Kolkata
      PGTZ: Asia/Kolkata
      POSTGRES_INITDB_ARGS: '--data-checksums --encoding=UTF8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8 --no-locale'
    command: ["postgres", "-c", "timezone=Asia/Kolkata", "-c", "log_timezone=Asia/Kolkata"]
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jwt_user -d jwt_auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pgdata: